### ISSUE TITLE
Cleanup description

### ISSUE THREAD

**Issue by bsonnek** [intelequia/VirtualLabs#1]
As far as I know, this script has noting to do with Azure Automation and runbooks. This is a powershell script that runs directly on the RD Connection Broker and uses scheduled tasks on the local server.  Please correct me if i'm wrong, because i'd love to get this off the RD CB server.

Also please fix the "Azure Resource Management Mode" This should refer to the Azure Resource Management Module for powershell. 

Other than those fixes. thanks for your write up, this helped clear things up.

**Comment by davidjrh** [comment]
Hi @bsonnek , 

I have reviewed the description and are OK as they are. Here some clarifications:
1. Yes, this is a powershell script that runs directly on the RD Connection Broker and uses scheduled tasks on the local server. You need to create a Service Principal on the Azure AD to allow the powershell script to use the ARM API that scales the numbers of servers;
2. The "mode" is ok, it refers to the ARM mode instead of the "Classic" mode. This was written two years ago when documenting the between classing and ARM modes were necessary.
